services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arpf-ti-app
    volumes:
      # Re-add volume mount for the database directory
      - db_data:/app/db_volume
      - log_data:/app/logs      # Mount logs directory using a named volume
      # Optional: Mount media files if your app uses them
      # - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env # Load environment variables from .env file
    # Re-add environment variable for DB path
    environment:
      - DJANGO_DB_PATH=/app/db_volume/db.sqlite3
    # Entrypoint will handle migrations and starting Gunicorn
    # command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "arpf_ti.wsgi:application"]
    entrypoint: /app/entrypoint.sh

volumes:
  # Re-add db_data volume
  db_data:
  log_data: # Declare the named volume for logs
  # media_data: # Declare the named volume for media if used