# Generated by Django 4.2.20 on 2025-04-23 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_host', models.CharField(help_text='Target host to proxy requests to (e.g., example.com)', max_length=255)),
                ('target_port', models.IntegerField(default=80)),
                ('use_https', models.BooleanField(default=True)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('preserve_host_header', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('ip', 'IP Address'), ('country', 'Country Code'), ('user_agent', 'User Agent'), ('path', 'URL Path'), ('header', 'HTTP Header'), ('method', 'HTTP Method'), ('custom', 'Custom Rule')], max_length=20)),
                ('pattern', models.TextField(help_text='Pattern to match (regex supported)')),
                ('action', models.CharField(choices=[('block', 'Block'), ('allow', 'Allow'), ('log', 'Log Only'), ('alert', 'Alert')], default='block', max_length=20)),
                ('priority', models.IntegerField(default=100, help_text='Rules are processed in priority order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=2048)),
                ('method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('headers', models.JSONField(default=dict)),
                ('action_taken', models.CharField(max_length=20)),
                ('was_blocked', models.BooleanField(default=False)),
                ('response_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rule')),
            ],
        ),
    ]
