# Generated by Django 5.2 on 2025-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestlog_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='false_positive_count',
            field=models.IntegerField(default=0, help_text='Number of false positive matches'),
        ),
        migrations.AddField(
            model_name='rule',
            name='last_triggered',
            field=models.DateTimeField(blank=True, help_text='Last time this rule was triggered', null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually Created'), ('ai', 'AI Generated')], default='manual', help_text='Source of the rule creation', max_length=10),
        ),
        migrations.AddField(
            model_name='rule',
            name='true_positive_count',
            field=models.IntegerField(default=0, help_text='Number of true positive matches'),
        ),
    ]
