from django.db import models
from django.utils import timezone
from core.models import Rule, RequestLog

class Alert(models.Model):
    """
    The Alert model represents notifications generated by the WAF
    for suspicious or malicious activities.
    """
    ALERT_TYPES = [
        ('rule_match', 'Rule Match'),
        ('multiple_blocks', 'Multiple Blocks'),
        ('scan_detected', 'Scan Detected'),
        ('xss_attempt', 'XSS Attempt'),
        ('sqli_attempt', 'SQL Injection Attempt'),
        ('bot_activity', 'Bot Activity'),
        ('honeypot_hit', 'Honeypot Hit'),
        ('rate_limit', 'Rate Limit Exceeded'),
        ('geo_violation', 'Geographic Violation'),
        ('ai_detected', 'AI Model Detection'),
        ('other', 'Other')
    ]
    
    SEVERITY_LEVELS = [
        ('info', 'Informational'),
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical')
    ]
    
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES)
    severity = models.CharField(max_length=10, choices=SEVERITY_LEVELS, default='medium')
    title = models.CharField(max_length=255)
    description = models.TextField()
    source_ip = models.GenericIPAddressField(null=True, blank=True)
    triggered_rule = models.ForeignKey(Rule, on_delete=models.SET_NULL, null=True, blank=True)
    related_logs = models.ManyToManyField(RequestLog, blank=True)
    timestamp = models.DateTimeField(default=timezone.now)
    is_acknowledged = models.BooleanField(default=False)
    acknowledged_by = models.CharField(max_length=255, blank=True, null=True)
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.title} ({self.get_severity_display()} - {self.timestamp})"
    
    def acknowledge(self, user_name):
        """Mark the alert as acknowledged."""
        self.is_acknowledged = True
        self.acknowledged_by = user_name
        self.acknowledged_at = timezone.now()
        self.save()
    
    @property
    def created_at(self):
        """Backward compatibility for templates that use created_at instead of timestamp."""
        return self.timestamp


class AlertNotificationConfig(models.Model):
    """
    Configuration for alert notifications through various channels
    like email, Slack, webhooks, etc.
    """
    NOTIFICATION_TYPES = [
        ('email', 'Email'),
        ('slack', 'Slack'),
        ('webhook', 'Webhook'),
        ('sms', 'SMS')
    ]
    
    name = models.CharField(max_length=255)
    notification_type = models.CharField(max_length=10, choices=NOTIFICATION_TYPES)
    is_active = models.BooleanField(default=True)
    min_severity = models.CharField(max_length=10, choices=Alert.SEVERITY_LEVELS, default='medium',
                                  help_text="Minimum severity level to trigger this notification")
    recipients = models.TextField(help_text="Recipients, comma separated. For email: email addresses, for Slack: channel names, etc.")
    configuration = models.JSONField(default=dict, help_text="Configuration details specific to the notification type")
    
    def __str__(self):
        return f"{self.name} ({self.get_notification_type_display()})"
    
    def should_notify(self, alert):
        """Check if this alert should trigger a notification based on severity."""
        severity_order = dict((severity[0], i) for i, severity in enumerate(Alert.SEVERITY_LEVELS))
        return severity_order.get(alert.severity, 0) >= severity_order.get(self.min_severity, 0)
