# Generated by Django 4.2.20 on 2025-04-23 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('webhook', 'Webhook'), ('sms', 'SMS')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('min_severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Minimum severity level to trigger this notification', max_length=10)),
                ('recipients', models.TextField(help_text='Recipients, comma separated. For email: email addresses, for Slack: channel names, etc.')),
                ('configuration', models.JSONField(default=dict, help_text='Configuration details specific to the notification type')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rule_match', 'Rule Match'), ('multiple_blocks', 'Multiple Blocks'), ('scan_detected', 'Scan Detected'), ('xss_attempt', 'XSS Attempt'), ('sqli_attempt', 'SQL Injection Attempt'), ('bot_activity', 'Bot Activity'), ('honeypot_hit', 'Honeypot Hit'), ('rate_limit', 'Rate Limit Exceeded'), ('geo_violation', 'Geographic Violation'), ('ai_detected', 'AI Model Detection'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=255, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('related_logs', models.ManyToManyField(blank=True, to='core.requestlog')),
                ('triggered_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rule')),
            ],
        ),
    ]
