# Generated by Django 5.2 on 2025-04-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alertcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_status',
            field=models.CharField(choices=[('suggested', 'Suggested by Gemini'), ('confirmed', 'Confirmed and Sent'), ('ignored', 'Ignored'), ('standard', 'Standard Alert')], default='standard', help_text='Status of the alert for notification purposes', max_length=15),
        ),
        migrations.AddField(
            model_name='alert',
            name='gemini_suggestion',
            field=models.TextField(blank=True, help_text='Gemini AI suggestion about this alert', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether this alert has been sent to notification channels'),
        ),
    ]
