# Generated by Django 5.2 on 2025-04-30 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_alert_status_alert_gemini_suggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=50)),
                ('reasoning', models.TextField()),
                ('suggested_actions', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_rating', models.IntegerField(blank=True, help_text='Rating from 1-5 on how accurate the suggestion was', null=True)),
                ('feedback_notes', models.TextField(blank=True, help_text='Additional notes or comments about the suggestion')),
                ('feedback_provided_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestion', to='alerts.alert')),
                ('feedback_provided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
