# Generated by Django 4.2.20 on 2025-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiclassifiermodel',
            name='model_params',
            field=models.JSONField(blank=True, default=dict, help_text='Additional model parameters in JSON format'),
        ),
        migrations.AlterField(
            model_name='aiclassifiermodel',
            name='model_type',
            field=models.CharField(choices=[('random_forest', 'Random Forest'), ('naive_bayes', 'Naive Bayes'), ('neural_network', 'Neural Network'), ('gpt', 'GPT-based Model'), ('llama', 'Llama Model'), ('llama_quantized', 'Llama Quantized'), ('custom', 'Custom Model')], max_length=20),
        ),
    ]
