# Generated by Django 5.2 on 2025-04-28 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_intelligence', '0003_threatintelentry_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('ip', 'Single IP Address'), ('ip_range', 'IP Address Range/CIDR'), ('country', 'Country Code'), ('port', 'Single Port'), ('port_range', 'Port Range'), ('protocol', 'Protocol'), ('custom', 'Custom Expression')], max_length=20)),
                ('value', models.CharField(help_text='IP, CIDR, country code, etc.', max_length=255)),
                ('action', models.CharField(choices=[('block', 'Block'), ('allow', 'Allow'), ('log', 'Log Only')], default='block', max_length=20)),
                ('category', models.CharField(choices=[('security', 'Security'), ('compliance', 'Compliance'), ('traffic', 'Traffic Management'), ('custom', 'Custom')], default='security', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('both', 'Both Directions')], default='inbound', max_length=20)),
                ('protocol', models.CharField(blank=True, choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('http', 'HTTP'), ('https', 'HTTPS'), ('ftp', 'FTP'), ('ssh', 'SSH'), ('smtp', 'SMTP'), ('dns', 'DNS')], max_length=20, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('port_end', models.IntegerField(blank=True, help_text='End port for range', null=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of this rule (e.g. manual, auto, api)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
