# Generated by Django 5.2 on 2025-04-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_intelligence', '0005_suggestedfirewallrule_delete_aiclassifiermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatintelentry',
            name='is_test_data',
            field=models.BooleanField(default=False, help_text='Flag to mark test/dummy data'),
        ),
    ]
